name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-and-static-analysis:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      APP_DEBUG: "0"
      APP_SECRET: "ci_dummy_secret_ci_dummy_secret"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data_test.db"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: sqlite, pdo_sqlite
          coverage: none

      - name: Installer les dépendances Composer
        env:
          APP_ENV: test
          APP_DEBUG: "0"
          APP_SECRET: "ci_dummy_secret_ci_dummy_secret"
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data_test.db"
        run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-req=ext-pgsql

      - name: Préparer la base de test
        run: |
          mkdir -p var
          php bin/console doctrine:schema:drop --force --full-database --env=test || true
          php bin/console doctrine:migrations:migrate --env=test --no-interaction
          php bin/console doctrine:fixtures:load --env=test --no-interaction --purge-with-truncate

      - name: Lancer PHPStan
        run: vendor/bin/phpstan analyse --configuration=phpstan.dist.neon

      - name: Lancer les tests
        run: php bin/phpunit